server:
  port: 8050
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb:http://USER-SERVICE
          predicates:
            - Path=/api/v1/user/**
        - id: auth-service
          uri: lb:http://USER-SERVICE
          predicates:
            - Path=/api/v1/auth/**
        - id: order-service
          uri: lb:http://ORDER-SERVICE
          predicates:
            - Path=/api/v1/orders/**
        - id: product-service
          uri: lb:http://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/products/**
        - id: category-service
          uri: lb:http://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/category/**
